baseurl = "/"
languageCode = "en-us"
title = "Exp-AI docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "exp-ai"
	description = "Exp-AI place for documentations."
	copyright = ""

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/exp-ai/"

	version = ""
	logo = "images/logo.png"
	favicon = "images/logo.png"

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/custom.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	# Choose between blue, red, cyan, light-blue, purple, deep-purple, indigo, grey
	# blue-grey, brown, orange, deep-orange, amber, yellow, lime, green, light-green
	# teal
	[params.palette]
    	primary = "indigo"
    	accent  = "deep-orange"

    [params.font]
    	text = "Exo 2"
    	code = "Inconsolata"


[social]
	twitter = ""
	github  = "exp-ai"
	email   = "info@exp-ai.com"


[[menu.main]]
	name   = "Welcome guide"
	url    = "/"
	weight = 1

#[[menu.main]]
#	name   = "Getting started"
#	url    = "getting-started/"
#	weight = 10
#
#[[menu.main]]
#	name   = "Adding content"
#	url    = "adding-content/"
#	weight = 20
#
#[[menu.main]]
#	name   = "Roadmap"
#	url    = "roadmap/"
#	weight = 30
#
#[[menu.main]]
#	name   = "License"
#	url    = "license/"
#	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
